insert into carmine_universites
  (pays, etablissement, cursus, nature, filiere, domaine, source, millesime, consulte_le)
values
  ('Royaume-Uni', 'University of Oxford', 'Mathematics', 'offre_type', 'uk'::carmine_track, 'ox.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Oxford', 'Physics', 'offre_type', 'uk'::carmine_track, 'ox.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Oxford', 'Engineering Science', 'offre_type', 'uk'::carmine_track, 'ox.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Oxford', 'Computer Science', 'offre_type', 'uk'::carmine_track, 'ox.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Oxford', 'Economics and Management', 'offre_type', 'uk'::carmine_track, 'ox.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Oxford', 'Philosophy, Politics and Economics', 'offre_type', 'uk'::carmine_track, 'ox.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Oxford', 'Law', 'offre_type', 'uk'::carmine_track, 'ox.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Oxford', 'Medicine', 'offre_type', 'uk'::carmine_track, 'ox.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Oxford', 'History', 'offre_type', 'uk'::carmine_track, 'ox.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Oxford', 'Biochemistry', 'offre_type', 'uk'::carmine_track, 'ox.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Cambridge', 'Mathematics', 'offre_type', 'uk'::carmine_track, 'cam.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Cambridge', 'Economics', 'offre_type', 'uk'::carmine_track, 'cam.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Cambridge', 'Engineering', 'offre_type', 'uk'::carmine_track, 'cam.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Cambridge', 'Computer Science', 'offre_type', 'uk'::carmine_track, 'cam.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Cambridge', 'Law', 'offre_type', 'uk'::carmine_track, 'cam.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Cambridge', 'Medicine', 'offre_type', 'uk'::carmine_track, 'cam.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Cambridge', 'History', 'offre_type', 'uk'::carmine_track, 'cam.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Cambridge', 'Human, Social and Political Sciences', 'offre_type', 'uk'::carmine_track, 'cam.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'Imperial College London', 'Mathematics', 'offre_type', 'uk'::carmine_track, 'imperial.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'Imperial College London', 'Computing', 'offre_type', 'uk'::carmine_track, 'imperial.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'Imperial College London', 'Physics', 'offre_type', 'uk'::carmine_track, 'imperial.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'Imperial College London', 'Mechanical Engineering', 'offre_type', 'uk'::carmine_track, 'imperial.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'Imperial College London', 'Electrical and Electronic Engineering', 'offre_type', 'uk'::carmine_track, 'imperial.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'Imperial College London', 'Chemical Engineering', 'offre_type', 'uk'::carmine_track, 'imperial.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'Imperial College London', 'Aeronautical Engineering', 'offre_type', 'uk'::carmine_track, 'imperial.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'Imperial College London', 'Medicine', 'offre_type', 'uk'::carmine_track, 'imperial.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'Imperial College London', 'Economics, Finance and Data Science', 'offre_type', 'uk'::carmine_track, 'imperial.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'London School of Economics', 'Economics', 'offre_type', 'uk'::carmine_track, 'lse.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'London School of Economics', 'Mathematics and Economics', 'offre_type', 'uk'::carmine_track, 'lse.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'London School of Economics', 'Politics and International Relations', 'offre_type', 'uk'::carmine_track, 'lse.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'London School of Economics', 'Philosophy, Politics and Economics', 'offre_type', 'uk'::carmine_track, 'lse.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'London School of Economics', 'Law', 'offre_type', 'uk'::carmine_track, 'lse.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'London School of Economics', 'Management', 'offre_type', 'uk'::carmine_track, 'lse.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'London School of Economics', 'Data Science', 'offre_type', 'uk'::carmine_track, 'lse.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University College London', 'Mathematics', 'offre_type', 'uk'::carmine_track, 'ucl.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University College London', 'Computer Science', 'offre_type', 'uk'::carmine_track, 'ucl.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University College London', 'Mechanical Engineering', 'offre_type', 'uk'::carmine_track, 'ucl.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University College London', 'Law', 'offre_type', 'uk'::carmine_track, 'ucl.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University College London', 'Medicine', 'offre_type', 'uk'::carmine_track, 'ucl.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University College London', 'Physics', 'offre_type', 'uk'::carmine_track, 'ucl.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University College London', 'Politics and International Relations', 'offre_type', 'uk'::carmine_track, 'ucl.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Warwick', 'Economics', 'offre_type', 'uk'::carmine_track, 'warwick.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Warwick', 'Computer Science', 'offre_type', 'uk'::carmine_track, 'warwick.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Warwick', 'Philosophy, Politics and Economics', 'offre_type', 'uk'::carmine_track, 'warwick.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Warwick', 'Engineering', 'offre_type', 'uk'::carmine_track, 'warwick.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Warwick', 'Mathematics, Operational Research, Statistics and Economics', 'offre_type', 'uk'::carmine_track, 'warwick.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Edinburgh', 'Mathematics', 'offre_type', 'uk'::carmine_track, 'ed.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Edinburgh', 'Computer Science', 'offre_type', 'uk'::carmine_track, 'ed.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Edinburgh', 'Economics', 'offre_type', 'uk'::carmine_track, 'ed.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Edinburgh', 'Physics', 'offre_type', 'uk'::carmine_track, 'ed.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Edinburgh', 'Law', 'offre_type', 'uk'::carmine_track, 'ed.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Edinburgh', 'Medicine', 'offre_type', 'uk'::carmine_track, 'ed.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Edinburgh', 'Business', 'offre_type', 'uk'::carmine_track, 'ed.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of St Andrews', 'Mathematics', 'offre_type', 'uk'::carmine_track, 'st-andrews.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of St Andrews', 'Economics', 'offre_type', 'uk'::carmine_track, 'st-andrews.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of St Andrews', 'International Relations', 'offre_type', 'uk'::carmine_track, 'st-andrews.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of St Andrews', 'Computer Science', 'offre_type', 'uk'::carmine_track, 'st-andrews.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of St Andrews', 'Physics', 'offre_type', 'uk'::carmine_track, 'st-andrews.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of St Andrews', 'Medicine', 'offre_type', 'uk'::carmine_track, 'st-andrews.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'Durham University', 'Mathematics', 'offre_type', 'uk'::carmine_track, 'durham.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'Durham University', 'Economics', 'offre_type', 'uk'::carmine_track, 'durham.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'Durham University', 'Law', 'offre_type', 'uk'::carmine_track, 'durham.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'Durham University', 'Physics', 'offre_type', 'uk'::carmine_track, 'durham.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'Durham University', 'Computer Science', 'offre_type', 'uk'::carmine_track, 'durham.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'Durham University', 'Philosophy, Politics and Economics', 'offre_type', 'uk'::carmine_track, 'durham.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Bristol', 'Mathematics', 'offre_type', 'uk'::carmine_track, 'bristol.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Bristol', 'Economics', 'offre_type', 'uk'::carmine_track, 'bristol.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Bristol', 'Aerospace Engineering', 'offre_type', 'uk'::carmine_track, 'bristol.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Bristol', 'Computer Science', 'offre_type', 'uk'::carmine_track, 'bristol.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Bristol', 'Law', 'offre_type', 'uk'::carmine_track, 'bristol.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Bristol', 'Physics', 'offre_type', 'uk'::carmine_track, 'bristol.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'King''s College London', 'Law', 'offre_type', 'uk'::carmine_track, 'kcl.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'King''s College London', 'Mathematics', 'offre_type', 'uk'::carmine_track, 'kcl.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'King''s College London', 'Computer Science', 'offre_type', 'uk'::carmine_track, 'kcl.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'King''s College London', 'Medicine', 'offre_type', 'uk'::carmine_track, 'kcl.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Manchester', 'Mathematics', 'offre_type', 'uk'::carmine_track, 'manchester.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Manchester', 'Computer Science', 'offre_type', 'uk'::carmine_track, 'manchester.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Manchester', 'Economics', 'offre_type', 'uk'::carmine_track, 'manchester.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Manchester', 'Mechanical Engineering', 'offre_type', 'uk'::carmine_track, 'manchester.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Bath', 'Mathematics', 'offre_type', 'uk'::carmine_track, 'bath.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Bath', 'Economics', 'offre_type', 'uk'::carmine_track, 'bath.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Bath', 'Computer Science', 'offre_type', 'uk'::carmine_track, 'bath.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Royaume-Uni', 'University of Bath', 'Mechanical Engineering', 'offre_type', 'uk'::carmine_track, 'bath.ac.uk', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('France', 'Lycée Louis-le-Grand', 'CPGE MPSI', 'eligibilite', null, 'louislegrand.fr', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('France', 'Lycée Louis-le-Grand', 'CPGE PCSI', 'eligibilite', null, 'louislegrand.fr', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('France', 'Lycée Louis-le-Grand', 'CPGE ECG', 'eligibilite', null, 'louislegrand.fr', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('France', 'Lycée Louis-le-Grand', 'CPGE BCPST', 'eligibilite', null, 'louislegrand.fr', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('France', 'Lycée Henri-IV', 'CPGE MPSI', 'eligibilite', null, 'lycee-henri4.fr', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('France', 'Lycée Henri-IV', 'CPGE PCSI', 'eligibilite', null, 'lycee-henri4.fr', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('France', 'Lycée Henri-IV', 'CPGE BCPST', 'eligibilite', null, 'lycee-henri4.fr', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('France', 'Lycée Henri-IV', 'CPGE B/L', 'eligibilite', null, 'lycee-henri4.fr', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('France', 'Lycée Stanislas', 'CPGE PCSI', 'eligibilite', null, 'stanislas.fr', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('France', 'Lycée Stanislas', 'CPGE ECG', 'eligibilite', null, 'stanislas.fr', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('France', 'Lycée Stanislas', 'CPGE BCPST', 'eligibilite', null, 'stanislas.fr', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('France', 'Lycée Sainte-Geneviève', 'CPGE MPSI', 'eligibilite', null, 'bginette.com', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('France', 'Lycée Sainte-Geneviève', 'CPGE PCSI', 'eligibilite', null, 'bginette.com', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('France', 'Lycée Sainte-Geneviève', 'CPGE ECG', 'eligibilite', null, 'bginette.com', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('France', 'Lycée Sainte-Geneviève', 'CPGE BCPST', 'eligibilite', null, 'bginette.com', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('France', 'Lycée Saint-Louis', 'CPGE MPSI', 'eligibilite', null, 'lycee-saintlouis.fr', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('France', 'Lycée Saint-Louis', 'CPGE PCSI', 'eligibilite', null, 'lycee-saintlouis.fr', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('France', 'Lycée Saint-Louis', 'CPGE BCPST', 'eligibilite', null, 'lycee-saintlouis.fr', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('France', 'Lycée Janson-de-Sailly', 'CPGE MPSI', 'eligibilite', null, 'janson-de-sailly.fr', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('France', 'Lycée Janson-de-Sailly', 'CPGE PCSI', 'eligibilite', null, 'janson-de-sailly.fr', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('France', 'Lycée Janson-de-Sailly', 'CPGE ECG', 'eligibilite', null, 'janson-de-sailly.fr', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('France', 'Lycée Hoche', 'CPGE MPSI', 'eligibilite', null, 'lyc-hoche-versailles.ac-versailles.fr', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('France', 'Lycée Hoche', 'CPGE PCSI', 'eligibilite', null, 'lyc-hoche-versailles.ac-versailles.fr', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('France', 'Lycée Hoche', 'CPGE ECG', 'eligibilite', null, 'lyc-hoche-versailles.ac-versailles.fr', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('France', 'Lycée du Parc', 'CPGE MPSI', 'eligibilite', null, 'lyceeduparc.fr', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('France', 'Lycée du Parc', 'CPGE PCSI', 'eligibilite', null, 'lyceeduparc.fr', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('France', 'Lycée du Parc', 'CPGE ECG', 'eligibilite', null, 'lyceeduparc.fr', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('France', 'Sciences Po Paris', 'Collège universitaire', 'eligibilite', null, 'sciencespo.fr', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Suisse', 'EPFL', 'Informatique', 'eligibilite', 'eu'::carmine_track, 'epfl.ch', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Suisse', 'EPFL', 'Physique', 'eligibilite', 'eu'::carmine_track, 'epfl.ch', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Suisse', 'EPFL', 'Génie électrique et électronique', 'eligibilite', 'eu'::carmine_track, 'epfl.ch', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Suisse', 'ETH Zurich', 'Informatik', 'eligibilite', 'eu'::carmine_track, 'ethz.ch', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Suisse', 'ETH Zurich', 'Mathematik', 'eligibilite', 'eu'::carmine_track, 'ethz.ch', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Suisse', 'ETH Zurich', 'Physik', 'eligibilite', 'eu'::carmine_track, 'ethz.ch', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Suisse', 'ETH Zurich', 'Maschineningenieurwissenschaften', 'eligibilite', 'eu'::carmine_track, 'ethz.ch', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Italie', 'Università Bocconi', 'Economics and Management', 'seuil_points', 'eu'::carmine_track, 'unibocconi.eu', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Italie', 'Università Bocconi', 'Economics, Management and Computer Science', 'seuil_points', 'eu'::carmine_track, 'unibocconi.eu', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Pays-Bas', 'TU Delft', 'Aerospace Engineering', 'eligibilite', 'eu'::carmine_track, 'tudelft.nl', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Pays-Bas', 'TU Delft', 'Computer Science and Engineering', 'eligibilite', 'eu'::carmine_track, 'tudelft.nl', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Pays-Bas', 'Universiteit van Amsterdam', 'Economics and Business Economics', 'eligibilite', 'eu'::carmine_track, 'uva.nl', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Pays-Bas', 'Universiteit van Amsterdam', 'Politics, Psychology, Law and Economics', 'eligibilite', 'eu'::carmine_track, 'uva.nl', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Irlande', 'Trinity College Dublin', 'Mathematics', 'seuil_points', 'eu'::carmine_track, 'tcd.ie', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Irlande', 'Trinity College Dublin', 'Computer Science', 'seuil_points', 'eu'::carmine_track, 'tcd.ie', 'Site de l’établissement', '2026-27', '2026-09-09'),
  ('Irlande', 'Trinity College Dublin', 'Economics', 'seuil_points', 'eu'::carmine_track, 'tcd.ie', 'Site de l’établissement', '2026-27', '2026-09-09')
on conflict (pays, etablissement, (coalesce(cursus, ''))) do update
  set filiere = coalesce(carmine_universites.filiere, excluded.filiere),
      domaine = coalesce(carmine_universites.domaine, excluded.domaine);

update carmine_universites set domaine = 'cam.ac.uk' where etablissement = 'University of Cambridge' and domaine is null;
update carmine_universites set domaine = 'warwick.ac.uk' where etablissement = 'University of Warwick' and domaine is null;
update carmine_universites set domaine = 'ucl.ac.uk' where etablissement = 'University College London' and domaine is null;
update carmine_universites set domaine = 'kcl.ac.uk' where etablissement = 'King''s College London' and domaine is null;
update carmine_universites set domaine = 'epfl.ch' where etablissement = 'EPFL' and domaine is null;
update carmine_universites set domaine = 'unibocconi.eu' where etablissement = 'Università Bocconi' and domaine is null;
update carmine_universites set domaine = 'stanislas.fr' where etablissement = 'Lycée Stanislas' and domaine is null;
update carmine_universites set domaine = 'bginette.com' where etablissement = 'Lycée Sainte-Geneviève' and domaine is null;
