import { defineConfig } from 'vite';
import { resolve } from 'path';

export default defineConfig({
  root: '.',
  publicDir: 'public',
  build: {
    outDir: 'dist',
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        coursParticuliers: resolve(__dirname, 'cours-particuliers.html'),
        about: resolve(__dirname, 'about.html'),
        temoignages: resolve(__dirname, 'temoignages.html'),
        consultingAdmissions: resolve(__dirname, 'consulting-admissions.html'),
        admissionEcoles: resolve(__dirname, 'admission-ecoles-paris.html'),
        thankYou: resolve(__dirname, 'thank-you.html'),
        notFound: resolve(__dirname, '404.html'),
        legal: resolve(__dirname, 'mentions-legales.html'),
        privacy: resolve(__dirname, 'confidentialite.html'),
        espaceClient: resolve(__dirname, 'espace-client.html'),
        demo: resolve(__dirname, 'demo.html'),
        ressources: resolve(__dirname, 'ressources.html'),
        pilotage: resolve(__dirname, 'pilotage.html'),
        // Moteur de pilotage, construit à côté du portail ; non lié depuis le site.
        moteur: resolve(__dirname, 'moteur.html'),
        dossier: resolve(__dirname, 'dossier.html'),
        blog: resolve(__dirname, 'blog.html'),
        // Pages vitrine anglaises, générées au prebuild par scripts/genere-pages-en.mjs
        enIndex: resolve(__dirname, 'en/index.html'),
        enConsultingAdmissions: resolve(__dirname, 'en/consulting-admissions.html'),
        enAdmissionEcoles: resolve(__dirname, 'en/admission-ecoles-paris.html'),
        enCoursParticuliers: resolve(__dirname, 'en/cours-particuliers.html'),
        enAbout: resolve(__dirname, 'en/about.html'),
        enTemoignages: resolve(__dirname, 'en/temoignages.html'),
        enRessources: resolve(__dirname, 'en/ressources.html'),
        blogEn: resolve(__dirname, 'blog/en/index.html'),
        // FR blog articles (50)
        blogAdmissionJeannineManuel6eme4eme2nde: resolve(__dirname, 'blog/admission-jeannine-manuel-6eme-4eme-2nde.html'),
        blogBfiJeannineManuelPostBac: resolve(__dirname, 'blog/bfi-jeannine-manuel-post-bac.html'),
        blogChocMathematiqueJeannineManuel: resolve(__dirname, 'blog/choc-mathematique-jeannine-manuel.html'),
        blogCommentEntrerJeannineManuelGuide: resolve(__dirname, 'blog/comment-entrer-jeannine-manuel-guide.html'),
        blogCoursMathsCursusFrancaisBruxelles: resolve(__dirname, 'blog/cours-maths-cursus-francais-bruxelles.html'),
        blogCoursMathsCursusFrancaisDubai: resolve(__dirname, 'blog/cours-maths-cursus-francais-dubai.html'),
        blogCoursMathsCursusFrancaisGeneve: resolve(__dirname, 'blog/cours-maths-cursus-francais-geneve.html'),
        blogCoursMathsCursusFrancaisHongKong: resolve(__dirname, 'blog/cours-maths-cursus-francais-hong-kong.html'),
        blogCoursMathsCursusFrancaisLondres: resolve(__dirname, 'blog/cours-maths-cursus-francais-londres.html'),
        blogCoursMathsCursusFrancaisNewYork: resolve(__dirname, 'blog/cours-maths-cursus-francais-new-york.html'),
        blogCoursMathsCursusFrancaisShanghai: resolve(__dirname, 'blog/cours-maths-cursus-francais-shanghai.html'),
        blogCoursMathsCursusFrancaisSingapour: resolve(__dirname, 'blog/cours-maths-cursus-francais-singapour.html'),
        blogCoursMathsCursusFrancaisTaiwan: resolve(__dirname, 'blog/cours-maths-cursus-francais-taiwan.html'),
        blogCoursMathsCursusFrancaisTokyo: resolve(__dirname, 'blog/cours-maths-cursus-francais-tokyo.html'),
        blogCoursMathsEcoleAlsacienne: resolve(__dirname, 'blog/cours-maths-ecole-alsacienne.html'),
        blogCoursMathsEcolesInternationalesParis: resolve(__dirname, 'blog/cours-maths-ecoles-internationales-paris.html'),
        blogCoursMathsFranklin: resolve(__dirname, 'blog/cours-maths-franklin.html'),
        blogCoursMathsHenri4: resolve(__dirname, 'blog/cours-maths-henri-4.html'),
        blogCoursMathsJeannineManuel: resolve(__dirname, 'blog/cours-maths-jeannine-manuel.html'),
        blogCoursMathsLaTour: resolve(__dirname, 'blog/cours-maths-la-tour.html'),
        blogCoursMathsLyceeInternationalSaintGermain: resolve(__dirname, 'blog/cours-maths-lycee-international-saint-germain.html'),
        blogCoursMathsSaintJeanDePassy: resolve(__dirname, 'blog/cours-maths-saint-jean-de-passy.html'),
        blogDebouchesApresJeannineManuel: resolve(__dirname, 'blog/debouches-apres-jeannine-manuel.html'),
        blogDifficultesMathsLyceeBilingue: resolve(__dirname, 'blog/difficultes-maths-lycee-bilingue.html'),
        blogForceEcoleJeannineManuel: resolve(__dirname, 'blog/force-ecole-jeannine-manuel.html'),
        blogEntrerBocconiDepuisLyceeFrancais: resolve(__dirname, 'blog/entrer-bocconi-depuis-lycee-francais.html'),
        blogPasserLeSatDepuisLaFrance: resolve(__dirname, 'blog/passer-le-sat-depuis-la-france.html'),
        blogEntrerSaintJeanDePassyInscription: resolve(__dirname, 'blog/entrer-saint-jean-de-passy-inscription.html'),
        blogEntrerEcoleAlsacienneAdmission: resolve(__dirname, 'blog/entrer-ecole-alsacienne-admission.html'),
        blogEntrerFranklinSaintLouisDeGonzague: resolve(__dirname, 'blog/entrer-franklin-saint-louis-de-gonzague.html'),
        blogLyceeFrancaisInternationalBangkokLfibAdmissionPrix: resolve(__dirname, 'blog/lycee-francais-international-bangkok-lfib-admission-prix.html'),
        blogLyceeFrancaisNewYorkAdmissionTestPrix: resolve(__dirname, 'blog/lycee-francais-new-york-admission-test-prix.html'),
        blogEntrerCollegeStanislasInscription: resolve(__dirname, 'blog/entrer-college-stanislas-inscription.html'),
        blogEntrerCollegeSevigneAdmission: resolve(__dirname, 'blog/entrer-college-sevigne-admission.html'),
        blogIbOuBacFrancais: resolve(__dirname, 'blog/ib-ou-bac-francais.html'),
        blogEnWhichPrepaWithWhichGrades: resolve(__dirname, 'blog/en/which-prepa-with-which-grades.html'),
        blogEnMpsiPrepaGradesNeeded: resolve(__dirname, 'blog/en/mpsi-prepa-grades-needed.html'),
        blogEnPcsiPrepaGradesNeeded: resolve(__dirname, 'blog/en/pcsi-prepa-grades-needed.html'),
        blogEnCollegeSevigneAdmission: resolve(__dirname, 'blog/en/college-sevigne-admission.html'),
        blogEnStanislasParisAdmission: resolve(__dirname, 'blog/en/stanislas-paris-admission.html'),
        blogEnEcoleAlsacienneAdmission: resolve(__dirname, 'blog/en/ecole-alsacienne-admission.html'),
        blogEnEcgBusinessPrepaGradesNeeded: resolve(__dirname, 'blog/en/ecg-business-prepa-grades-needed.html'),
        blogEnBcpstPrepaGradesNeeded: resolve(__dirname, 'blog/en/bcpst-prepa-grades-needed.html'),
        blogEnIbOrFrenchBaccalaureate: resolve(__dirname, 'blog/en/ib-or-french-baccalaureate.html'),
        blogEnFranklinSaintLouisDeGonzagueAdmission: resolve(__dirname, 'blog/en/franklin-saint-louis-de-gonzague-admission.html'),
        blogEnSaintJeanDePassyAdmission: resolve(__dirname, 'blog/en/saint-jean-de-passy-admission.html'),
        blogEnLyceeFrancaisBangkokLfibAdmissionFees: resolve(__dirname, 'blog/en/lycee-francais-bangkok-lfib-admission-fees.html'),
        blogEnLyceeFrancaisNewYorkAdmissionFees: resolve(__dirname, 'blog/en/lycee-francais-new-york-admission-fees.html'),
        blogPourquoiApprendreLeChinoisEnfant: resolve(__dirname, 'blog/pourquoi-apprendre-le-chinois-enfant.html'),
        blogEnWhyLearnChineseChild: resolve(__dirname, 'blog/en/why-learn-chinese-child.html'),
        blogChinoisCollegeParis: resolve(__dirname, 'blog/chinois-college-paris-lv2-section-internationale.html'),
        blogEnChineseMiddleSchoolParis: resolve(__dirname, 'blog/en/chinese-middle-school-paris.html'),
        blogPreparerOlympiadesMaths: resolve(__dirname, 'blog/preparer-olympiades-maths.html'),
        blogEnPreparingFrenchMathsOlympiads: resolve(__dirname, 'blog/en/preparing-french-maths-olympiads.html'),
        blogOlympiadesMathsDossierParcoursup: resolve(__dirname, 'blog/olympiades-maths-dossier-parcoursup.html'),
        blogEnMathsOlympiadsUniversityApplication: resolve(__dirname, 'blog/en/maths-olympiads-university-application.html'),
        blogConcoursGeneralMathsPreparation: resolve(__dirname, 'blog/concours-general-maths-preparation.html'),
        blogEnFrenchConcoursGeneralMaths: resolve(__dirname, 'blog/en/french-concours-general-maths.html'),
        blogKangourouOlympiadesAnimath: resolve(__dirname, 'blog/kangourou-olympiades-animath-par-ou-commencer.html'),
        blogEnMathsCompetitionsFranceByAge: resolve(__dirname, 'blog/en/maths-competitions-france-by-age.html'),
        blogQuelleEcoleInternationaleChoisirParis: resolve(__dirname, 'blog/quelle-ecole-internationale-choisir-paris.html'),
        blogEnChoosingInternationalSchoolParis: resolve(__dirname, 'blog/en/choosing-international-school-paris.html'),
        blogPreparerEntreeSixiemeCollegeSelectif: resolve(__dirname, 'blog/preparer-entree-sixieme-college-selectif.html'),
        blogEnPreparingForSixiemeSelectiveMiddleSchoolParis: resolve(__dirname, 'blog/en/preparing-for-sixieme-selective-middle-school-paris.html'),
        blogSatMathsLyceeFrancais: resolve(__dirname, 'blog/sat-maths-lycee-francais.html'),
        blogEnSatMathFrenchLycee: resolve(__dirname, 'blog/en/sat-math-french-lycee.html'),
        blogTestsAdmissionOxfordCambridge: resolve(__dirname, 'blog/tests-admission-oxford-cambridge.html'),
        blogEnOxfordCambridgeAdmissionsTests: resolve(__dirname, 'blog/en/oxford-cambridge-admissions-tests.html'),
        blogTmuaPreparationLyceeFrancais: resolve(__dirname, 'blog/tmua-preparation-lycee-francais.html'),
        blogEnTmuaPreparationFrenchLycee: resolve(__dirname, 'blog/en/tmua-preparation-french-lycee.html'),
        blogPourquoiPreparerOlympiadesMathematiques: resolve(__dirname, 'blog/pourquoi-preparer-olympiades-mathematiques.html'),
        blogEnIsMathsOlympiadWorthIt: resolve(__dirname, 'blog/en/is-maths-olympiad-worth-it.html'),
        blogEthZurichBacFrancaisAdmission: resolve(__dirname, 'blog/eth-zurich-bac-francais-admission.html'),
        blogEnEthZurichAdmissionFrenchBaccalaureate: resolve(__dirname, 'blog/en/eth-zurich-admission-french-baccalaureate.html'),
        blogQuellePrepaAvecQuelleMoyenne: resolve(__dirname, 'blog/quelle-prepa-avec-quelle-moyenne.html'),
        blogQuelleMoyennePourUneMpsi: resolve(__dirname, 'blog/quelle-moyenne-pour-une-mpsi.html'),
        blogQuelleMoyennePourUnePcsi: resolve(__dirname, 'blog/quelle-moyenne-pour-une-pcsi.html'),
        blogQuelleMoyennePourUnePrepaEcg: resolve(__dirname, 'blog/quelle-moyenne-pour-une-prepa-ecg.html'),
        blogQuelleMoyennePourUneBcpst: resolve(__dirname, 'blog/quelle-moyenne-pour-une-bcpst.html'),
        blogEpflAdmissionBacFrancaisCalendrier: resolve(__dirname, 'blog/epfl-admission-bac-francais-calendrier.html'),
        blogEntrerInstitutLeRoseyAdmissionExamenPrix: resolve(__dirname, 'blog/entrer-institut-le-rosey-admission-examen-prix.html'),
        blogIntegrerEpflDepuisLyceeFrancais: resolve(__dirname, 'blog/integrer-epfl-depuis-lycee-francais.html'),
        blogIntegrerIvyLeagueDepuisFrance: resolve(__dirname, 'blog/integrer-ivy-league-depuis-france.html'),
        blogIntegrerJeannineManuelInternational: resolve(__dirname, 'blog/integrer-jeannine-manuel-international.html'),
        blogJeannineManuelRefuseAlternatives: resolve(__dirname, 'blog/jeannine-manuel-refuse-alternatives.html'),
        blogJeannineManuelVsSaintGermain: resolve(__dirname, 'blog/jeannine-manuel-vs-saint-germain.html'),
        blogListeAttenteJeannineManuel: resolve(__dirname, 'blog/liste-attente-jeannine-manuel.html'),
        blogOptimiserChancesIntegrerJeannineManuel: resolve(__dirname, 'blog/optimiser-chances-integrer-jeannine-manuel.html'),
        blogParcoursupRetourExpatriation: resolve(__dirname, 'blog/parcoursup-retour-expatriation.html'),
        blogPasserDe12A16MathsLyceeInternational: resolve(__dirname, 'blog/passer-de-12-a-16-maths-lycee-international.html'),
        blogPourquoiJeannineManuelMeilleureEcole: resolve(__dirname, 'blog/pourquoi-jeannine-manuel-meilleure-ecole.html'),
        blogPreparationTestsJeannineManuelCarmine: resolve(__dirname, 'blog/preparation-tests-jeannine-manuel-carmine.html'),
        blogPreparerOralAdmissionJeannineManuel: resolve(__dirname, 'blog/preparer-oral-admission-jeannine-manuel.html'),
        blogProfilInternationalAvantageOuHandicapAdmissions: resolve(__dirname, 'blog/profil-international-avantage-ou-handicap-admissions.html'),
        blogProfilSpecifiqueJeannineManuel: resolve(__dirname, 'blog/profil-specifique-jeannine-manuel.html'),
        blogQuandCommencerPreparerAdmissionsPostBac: resolve(__dirname, 'blog/quand-commencer-preparer-admissions-post-bac.html'),
        blogQuelCollegeParisRetourExpatriation: resolve(__dirname, 'blog/quel-college-paris-retour-expatriation.html'),
        blogQuelLyceeParisRetourExpatriation: resolve(__dirname, 'blog/quel-lycee-paris-retour-expatriation.html'),
        blogQuelleEcolePrimaireParisRetourExpatriation: resolve(__dirname, 'blog/quelle-ecole-primaire-paris-retour-expatriation.html'),
        blogSePreparerTestIntegrationJeannineManuel: resolve(__dirname, 'blog/se-preparer-test-integration-jeannine-manuel.html'),
        blogTestIntegrationJeannineManuel: resolve(__dirname, 'blog/test-integration-jeannine-manuel.html'),
        blogQuelleEcoleChoisirDubaiGuide2026: resolve(__dirname, 'blog/quelle-ecole-choisir-dubai-guide-2026.html'),
        // EN blog articles
        blogEnBestHighSchoolParisReturningExpats: resolve(__dirname, 'blog/en/best-high-school-paris-returning-expats.html'),
        blogEnBestMiddleSchoolParisReturningExpats: resolve(__dirname, 'blog/en/best-middle-school-paris-returning-expats.html'),
        blogEnBestPrimarySchoolParisReturningExpats: resolve(__dirname, 'blog/en/best-primary-school-paris-returning-expats.html'),
        blogEnCarmineJeannineManuelTestPreparation: resolve(__dirname, 'blog/en/carmine-jeannine-manuel-test-preparation.html'),
        blogEnFrenchMathTutoringBrussels: resolve(__dirname, 'blog/en/french-math-tutoring-brussels.html'),
        blogEnFrenchMathTutoringDubai: resolve(__dirname, 'blog/en/french-math-tutoring-dubai.html'),
        blogEnFrenchMathTutoringGeneva: resolve(__dirname, 'blog/en/french-math-tutoring-geneva.html'),
        blogEnFrenchMathTutoringHongKong: resolve(__dirname, 'blog/en/french-math-tutoring-hong-kong.html'),
        blogEnFrenchMathTutoringLondon: resolve(__dirname, 'blog/en/french-math-tutoring-london.html'),
        blogEnFrenchMathTutoringNewYork: resolve(__dirname, 'blog/en/french-math-tutoring-new-york.html'),
        blogEnFrenchMathTutoringShanghai: resolve(__dirname, 'blog/en/french-math-tutoring-shanghai.html'),
        blogEnFrenchMathTutoringSingapore: resolve(__dirname, 'blog/en/french-math-tutoring-singapore.html'),
        blogEnFrenchMathTutoringTaiwan: resolve(__dirname, 'blog/en/french-math-tutoring-taiwan.html'),
        blogEnFrenchMathTutoringTokyo: resolve(__dirname, 'blog/en/french-math-tutoring-tokyo.html'),
        blogEnGettingIntoEpflFromFrenchHighSchool: resolve(__dirname, 'blog/en/getting-into-epfl-from-french-high-school.html'),
        blogEnEpflAdmissionFrenchBaccalaureate: resolve(__dirname, 'blog/en/epfl-admission-french-baccalaureate.html'),
        blogEnBocconiAdmissionFrenchBaccalaureate: resolve(__dirname, 'blog/en/bocconi-admission-french-baccalaureate.html'),
        blogEnTakingTheSatFromFrance: resolve(__dirname, 'blog/en/taking-the-sat-from-france.html'),
        blogEnHowToGetIntoLeRosey: resolve(__dirname, 'blog/en/how-to-get-into-le-rosey.html'),
        blogEnGettingIntoIvyLeagueFromFrance: resolve(__dirname, 'blog/en/getting-into-ivy-league-from-france.html'),
        blogEnHowToGetIntoJeannineManuel: resolve(__dirname, 'blog/en/how-to-get-into-jeannine-manuel.html'),
        blogEnImproveMathGradesInternationalSchool: resolve(__dirname, 'blog/en/improve-math-grades-international-school.html'),
        blogEnInternationalProfileAdvantageOrHandicapFrenchAdmissions: resolve(__dirname, 'blog/en/international-profile-advantage-or-handicap-french-admissions.html'),
        blogEnJeannineManuelAcademicExcellence: resolve(__dirname, 'blog/en/jeannine-manuel-academic-excellence.html'),
        blogEnJeannineManuelAdmissionByGradeLevel: resolve(__dirname, 'blog/en/jeannine-manuel-admission-by-grade-level.html'),
        blogEnJeannineManuelBfiPostGraduationImpact: resolve(__dirname, 'blog/en/jeannine-manuel-bfi-post-graduation-impact.html'),
        blogEnJeannineManuelEntryTestGuide: resolve(__dirname, 'blog/en/jeannine-manuel-entry-test-guide.html'),
        blogEnJeannineManuelIdealStudentProfile: resolve(__dirname, 'blog/en/jeannine-manuel-ideal-student-profile.html'),
        blogEnJeannineManuelMathGap: resolve(__dirname, 'blog/en/jeannine-manuel-math-gap.html'),
        blogEnJeannineManuelRejectedAlternatives: resolve(__dirname, 'blog/en/jeannine-manuel-rejected-alternatives.html'),
        blogEnJeannineManuelReturningFromAbroad: resolve(__dirname, 'blog/en/jeannine-manuel-returning-from-abroad.html'),
        blogEnJeannineManuelUniversityOutcomes: resolve(__dirname, 'blog/en/jeannine-manuel-university-outcomes.html'),
        blogEnJeannineManuelVsSaintGermainComparison: resolve(__dirname, 'blog/en/jeannine-manuel-vs-saint-germain-comparison.html'),
        blogEnJeannineManuelWaitlistStrategy: resolve(__dirname, 'blog/en/jeannine-manuel-waitlist-strategy.html'),
        blogEnMathStrugglesBilingualSchool: resolve(__dirname, 'blog/en/math-struggles-bilingual-school.html'),
        blogEnMathTutoringEcoleAlsacienne: resolve(__dirname, 'blog/en/math-tutoring-ecole-alsacienne.html'),
        blogEnMathTutoringFranklin: resolve(__dirname, 'blog/en/math-tutoring-franklin.html'),
        blogEnMathTutoringHenriIv: resolve(__dirname, 'blog/en/math-tutoring-henri-iv.html'),
        blogEnMathTutoringInternationalSchoolsParis: resolve(__dirname, 'blog/en/math-tutoring-international-schools-paris.html'),
        blogEnMathTutoringJeannineManuel: resolve(__dirname, 'blog/en/math-tutoring-jeannine-manuel.html'),
        blogEnMathTutoringLaTour: resolve(__dirname, 'blog/en/math-tutoring-la-tour.html'),
        blogEnMathTutoringLyceeInternationalSaintGermain: resolve(__dirname, 'blog/en/math-tutoring-lycee-international-saint-germain.html'),
        blogEnMathTutoringSaintJeanDePassy: resolve(__dirname, 'blog/en/math-tutoring-saint-jean-de-passy.html'),
        blogEnMaximizeChancesJeannineManuel: resolve(__dirname, 'blog/en/maximize-chances-jeannine-manuel.html'),
        blogEnParcoursupReturningExpatsGuide: resolve(__dirname, 'blog/en/parcoursup-returning-expats-guide.html'),
        blogEnPrepareJeannineManuelAdmissionInterview: resolve(__dirname, 'blog/en/prepare-jeannine-manuel-admission-interview.html'),
        blogEnPrepareJeannineManuelEntryTest: resolve(__dirname, 'blog/en/prepare-jeannine-manuel-entry-test.html'),
        blogEnWhenToStartPreparingUniversityAdmissions: resolve(__dirname, 'blog/en/when-to-start-preparing-university-admissions.html'),
        blogEnWhyJeannineManuelBestSchoolFrance: resolve(__dirname, 'blog/en/why-jeannine-manuel-best-school-france.html'),
        blogEnBestSchoolDubaiGuide2026: resolve(__dirname, 'blog/en/best-school-dubai-guide-2026.html'),
      },
    },
  },
  server: {
    port: 3000,
  },
});
