import { defineConfig } from 'vite';
import { resolve } from 'path';

export default defineConfig({
  root: '.',
  publicDir: 'public',
  build: {
    outDir: 'dist',
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        coursParticuliers: resolve(__dirname, 'cours-particuliers.html'),
        about: resolve(__dirname, 'about.html'),
        temoignages: resolve(__dirname, 'temoignages.html'),
        consultingAdmissions: resolve(__dirname, 'consulting-admissions.html'),
        thankYou: resolve(__dirname, 'thank-you.html'),
        notFound: resolve(__dirname, '404.html'),
        legal: resolve(__dirname, 'mentions-legales.html'),
        privacy: resolve(__dirname, 'confidentialite.html'),
        espaceClient: resolve(__dirname, 'espace-client.html'),
        demo: resolve(__dirname, 'demo.html'),
        ressources: resolve(__dirname, 'ressources.html'),
        pilotage: resolve(__dirname, 'pilotage.html'),
        blog: resolve(__dirname, 'blog.html'),
        // Pages vitrine anglaises, générées au prebuild par scripts/genere-pages-en.mjs
        enIndex: resolve(__dirname, 'en/index.html'),
        enConsultingAdmissions: resolve(__dirname, 'en/consulting-admissions.html'),
        enCoursParticuliers: resolve(__dirname, 'en/cours-particuliers.html'),
        enAbout: resolve(__dirname, 'en/about.html'),
        enTemoignages: resolve(__dirname, 'en/temoignages.html'),
        enRessources: resolve(__dirname, 'en/ressources.html'),
        blogEn: resolve(__dirname, 'blog/en/index.html'),
        // FR blog articles (50)
        blogAdmissionJeanineManuel6eme4eme2nde: resolve(__dirname, 'blog/admission-jeanine-manuel-6eme-4eme-2nde.html'),
        blogBfiJeanineManuelPostBac: resolve(__dirname, 'blog/bfi-jeanine-manuel-post-bac.html'),
        blogChocMathematiqueJeanineManuel: resolve(__dirname, 'blog/choc-mathematique-jeanine-manuel.html'),
        blogCommentEntrerJeanineManuelGuide: resolve(__dirname, 'blog/comment-entrer-jeanine-manuel-guide.html'),
        blogCoursMathsCursusFrancaisBruxelles: resolve(__dirname, 'blog/cours-maths-cursus-francais-bruxelles.html'),
        blogCoursMathsCursusFrancaisDubai: resolve(__dirname, 'blog/cours-maths-cursus-francais-dubai.html'),
        blogCoursMathsCursusFrancaisGeneve: resolve(__dirname, 'blog/cours-maths-cursus-francais-geneve.html'),
        blogCoursMathsCursusFrancaisHongKong: resolve(__dirname, 'blog/cours-maths-cursus-francais-hong-kong.html'),
        blogCoursMathsCursusFrancaisLondres: resolve(__dirname, 'blog/cours-maths-cursus-francais-londres.html'),
        blogCoursMathsCursusFrancaisNewYork: resolve(__dirname, 'blog/cours-maths-cursus-francais-new-york.html'),
        blogCoursMathsCursusFrancaisShanghai: resolve(__dirname, 'blog/cours-maths-cursus-francais-shanghai.html'),
        blogCoursMathsCursusFrancaisSingapour: resolve(__dirname, 'blog/cours-maths-cursus-francais-singapour.html'),
        blogCoursMathsCursusFrancaisTaiwan: resolve(__dirname, 'blog/cours-maths-cursus-francais-taiwan.html'),
        blogCoursMathsCursusFrancaisTokyo: resolve(__dirname, 'blog/cours-maths-cursus-francais-tokyo.html'),
        blogCoursMathsEcoleAlsacienne: resolve(__dirname, 'blog/cours-maths-ecole-alsacienne.html'),
        blogCoursMathsEcolesInternationalesParis: resolve(__dirname, 'blog/cours-maths-ecoles-internationales-paris.html'),
        blogCoursMathsFranklin: resolve(__dirname, 'blog/cours-maths-franklin.html'),
        blogCoursMathsHenri4: resolve(__dirname, 'blog/cours-maths-henri-4.html'),
        blogCoursMathsJeanineManuel: resolve(__dirname, 'blog/cours-maths-jeanine-manuel.html'),
        blogCoursMathsLaTour: resolve(__dirname, 'blog/cours-maths-la-tour.html'),
        blogCoursMathsLyceeInternationalSaintGermain: resolve(__dirname, 'blog/cours-maths-lycee-international-saint-germain.html'),
        blogCoursMathsSaintJeanDePassy: resolve(__dirname, 'blog/cours-maths-saint-jean-de-passy.html'),
        blogDebouchesApresJeanineManuel: resolve(__dirname, 'blog/debouches-apres-jeanine-manuel.html'),
        blogDifficultesMathsLyceeBilingue: resolve(__dirname, 'blog/difficultes-maths-lycee-bilingue.html'),
        blogForceEcoleJeanineManuel: resolve(__dirname, 'blog/force-ecole-jeanine-manuel.html'),
        blogIntegrerEpflDepuisLyceeFrancais: resolve(__dirname, 'blog/integrer-epfl-depuis-lycee-francais.html'),
        blogIntegrerIvyLeagueDepuisFrance: resolve(__dirname, 'blog/integrer-ivy-league-depuis-france.html'),
        blogIntegrerJeanineManuelInternational: resolve(__dirname, 'blog/integrer-jeanine-manuel-international.html'),
        blogJeanineManuelRefuseAlternatives: resolve(__dirname, 'blog/jeanine-manuel-refuse-alternatives.html'),
        blogJeanineManuelVsSaintGermain: resolve(__dirname, 'blog/jeanine-manuel-vs-saint-germain.html'),
        blogListeAttenteJeanineManuel: resolve(__dirname, 'blog/liste-attente-jeanine-manuel.html'),
        blogOptimiserChancesIntegrerJeanineManuel: resolve(__dirname, 'blog/optimiser-chances-integrer-jeanine-manuel.html'),
        blogParcoursupRetourExpatriation: resolve(__dirname, 'blog/parcoursup-retour-expatriation.html'),
        blogPasserDe12A16MathsLyceeInternational: resolve(__dirname, 'blog/passer-de-12-a-16-maths-lycee-international.html'),
        blogPourquoiJeanineManuelMeilleureEcole: resolve(__dirname, 'blog/pourquoi-jeanine-manuel-meilleure-ecole.html'),
        blogPreparationTestsJeanineManuelCarmine: resolve(__dirname, 'blog/preparation-tests-jeanine-manuel-carmine.html'),
        blogPreparerOralAdmissionJeanineManuel: resolve(__dirname, 'blog/preparer-oral-admission-jeanine-manuel.html'),
        blogProfilInternationalAvantageOuHandicapAdmissions: resolve(__dirname, 'blog/profil-international-avantage-ou-handicap-admissions.html'),
        blogProfilSpecifiqueJeanineManuel: resolve(__dirname, 'blog/profil-specifique-jeanine-manuel.html'),
        blogQuandCommencerPreparerAdmissionsPostBac: resolve(__dirname, 'blog/quand-commencer-preparer-admissions-post-bac.html'),
        blogQuelCollegeParisRetourExpatriation: resolve(__dirname, 'blog/quel-college-paris-retour-expatriation.html'),
        blogQuelLyceeParisRetourExpatriation: resolve(__dirname, 'blog/quel-lycee-paris-retour-expatriation.html'),
        blogQuelleEcolePrimaireParisRetourExpatriation: resolve(__dirname, 'blog/quelle-ecole-primaire-paris-retour-expatriation.html'),
        blogSePreparerTestIntegrationJeanineManuel: resolve(__dirname, 'blog/se-preparer-test-integration-jeanine-manuel.html'),
        blogTestIntegrationJeanineManuel: resolve(__dirname, 'blog/test-integration-jeanine-manuel.html'),
        blogQuelleEcoleChoisirDubaiGuide2026: resolve(__dirname, 'blog/quelle-ecole-choisir-dubai-guide-2026.html'),
        // EN blog articles
        blogEnBestHighSchoolParisReturningExpats: resolve(__dirname, 'blog/en/best-high-school-paris-returning-expats.html'),
        blogEnBestMiddleSchoolParisReturningExpats: resolve(__dirname, 'blog/en/best-middle-school-paris-returning-expats.html'),
        blogEnBestPrimarySchoolParisReturningExpats: resolve(__dirname, 'blog/en/best-primary-school-paris-returning-expats.html'),
        blogEnCarmineJeanineManuelTestPreparation: resolve(__dirname, 'blog/en/carmine-jeanine-manuel-test-preparation.html'),
        blogEnFrenchMathTutoringBrussels: resolve(__dirname, 'blog/en/french-math-tutoring-brussels.html'),
        blogEnFrenchMathTutoringDubai: resolve(__dirname, 'blog/en/french-math-tutoring-dubai.html'),
        blogEnFrenchMathTutoringGeneva: resolve(__dirname, 'blog/en/french-math-tutoring-geneva.html'),
        blogEnFrenchMathTutoringHongKong: resolve(__dirname, 'blog/en/french-math-tutoring-hong-kong.html'),
        blogEnFrenchMathTutoringLondon: resolve(__dirname, 'blog/en/french-math-tutoring-london.html'),
        blogEnFrenchMathTutoringNewYork: resolve(__dirname, 'blog/en/french-math-tutoring-new-york.html'),
        blogEnFrenchMathTutoringShanghai: resolve(__dirname, 'blog/en/french-math-tutoring-shanghai.html'),
        blogEnFrenchMathTutoringSingapore: resolve(__dirname, 'blog/en/french-math-tutoring-singapore.html'),
        blogEnFrenchMathTutoringTaiwan: resolve(__dirname, 'blog/en/french-math-tutoring-taiwan.html'),
        blogEnFrenchMathTutoringTokyo: resolve(__dirname, 'blog/en/french-math-tutoring-tokyo.html'),
        blogEnGettingIntoEpflFromFrenchHighSchool: resolve(__dirname, 'blog/en/getting-into-epfl-from-french-high-school.html'),
        blogEnGettingIntoIvyLeagueFromFrance: resolve(__dirname, 'blog/en/getting-into-ivy-league-from-france.html'),
        blogEnHowToGetIntoJeanineManuel: resolve(__dirname, 'blog/en/how-to-get-into-jeanine-manuel.html'),
        blogEnImproveMathGradesInternationalSchool: resolve(__dirname, 'blog/en/improve-math-grades-international-school.html'),
        blogEnInternationalProfileAdvantageOrHandicapFrenchAdmissions: resolve(__dirname, 'blog/en/international-profile-advantage-or-handicap-french-admissions.html'),
        blogEnJeanineManuelAcademicExcellence: resolve(__dirname, 'blog/en/jeanine-manuel-academic-excellence.html'),
        blogEnJeanineManuelAdmissionByGradeLevel: resolve(__dirname, 'blog/en/jeanine-manuel-admission-by-grade-level.html'),
        blogEnJeanineManuelBfiPostGraduationImpact: resolve(__dirname, 'blog/en/jeanine-manuel-bfi-post-graduation-impact.html'),
        blogEnJeanineManuelEntryTestGuide: resolve(__dirname, 'blog/en/jeanine-manuel-entry-test-guide.html'),
        blogEnJeanineManuelIdealStudentProfile: resolve(__dirname, 'blog/en/jeanine-manuel-ideal-student-profile.html'),
        blogEnJeanineManuelMathGap: resolve(__dirname, 'blog/en/jeanine-manuel-math-gap.html'),
        blogEnJeanineManuelRejectedAlternatives: resolve(__dirname, 'blog/en/jeanine-manuel-rejected-alternatives.html'),
        blogEnJeanineManuelReturningFromAbroad: resolve(__dirname, 'blog/en/jeanine-manuel-returning-from-abroad.html'),
        blogEnJeanineManuelUniversityOutcomes: resolve(__dirname, 'blog/en/jeanine-manuel-university-outcomes.html'),
        blogEnJeanineManuelVsSaintGermainComparison: resolve(__dirname, 'blog/en/jeanine-manuel-vs-saint-germain-comparison.html'),
        blogEnJeanineManuelWaitlistStrategy: resolve(__dirname, 'blog/en/jeanine-manuel-waitlist-strategy.html'),
        blogEnMathStrugglesBilingualSchool: resolve(__dirname, 'blog/en/math-struggles-bilingual-school.html'),
        blogEnMathTutoringEcoleAlsacienne: resolve(__dirname, 'blog/en/math-tutoring-ecole-alsacienne.html'),
        blogEnMathTutoringFranklin: resolve(__dirname, 'blog/en/math-tutoring-franklin.html'),
        blogEnMathTutoringHenriIv: resolve(__dirname, 'blog/en/math-tutoring-henri-iv.html'),
        blogEnMathTutoringInternationalSchoolsParis: resolve(__dirname, 'blog/en/math-tutoring-international-schools-paris.html'),
        blogEnMathTutoringJeanineManuel: resolve(__dirname, 'blog/en/math-tutoring-jeanine-manuel.html'),
        blogEnMathTutoringLaTour: resolve(__dirname, 'blog/en/math-tutoring-la-tour.html'),
        blogEnMathTutoringLyceeInternationalSaintGermain: resolve(__dirname, 'blog/en/math-tutoring-lycee-international-saint-germain.html'),
        blogEnMathTutoringSaintJeanDePassy: resolve(__dirname, 'blog/en/math-tutoring-saint-jean-de-passy.html'),
        blogEnMaximizeChancesJeanineManuel: resolve(__dirname, 'blog/en/maximize-chances-jeanine-manuel.html'),
        blogEnParcoursupReturningExpatsGuide: resolve(__dirname, 'blog/en/parcoursup-returning-expats-guide.html'),
        blogEnPrepareJeanineManuelAdmissionInterview: resolve(__dirname, 'blog/en/prepare-jeanine-manuel-admission-interview.html'),
        blogEnPrepareJeanineManuelEntryTest: resolve(__dirname, 'blog/en/prepare-jeanine-manuel-entry-test.html'),
        blogEnWhenToStartPreparingUniversityAdmissions: resolve(__dirname, 'blog/en/when-to-start-preparing-university-admissions.html'),
        blogEnWhyJeanineManuelBestSchoolFrance: resolve(__dirname, 'blog/en/why-jeanine-manuel-best-school-france.html'),
        blogEnBestSchoolDubaiGuide2026: resolve(__dirname, 'blog/en/best-school-dubai-guide-2026.html'),
      },
    },
  },
  server: {
    port: 3000,
  },
});
