/**
 * English layer for the milestone reference.
 * Loaded on demand — French visitors never download it.
 *
 * Only the human-readable fields are translated; ids, dates and structure live in
 * milestones.js and stay language-neutral.
 */

export const PHASES_EN = {
  0: { title: 'Groundwork', when: 'Years 7 to 9 (6e – 3e)',
    intro: "No application is being written yet: a student is being built. School and track choices, language level, first genuine commitments. This is also the year the transcript US universities will read quietly opens." },
  1: { title: 'Foundations', when: 'Year 10 (Seconde)',
    intro: 'The year of decisions that shape everything else. The specialist subjects chosen in spring determine which courses remain open three years later. Activities are pruned and the first substantial project begins.' },
  2: { title: 'Building', when: 'Year 11 (Première)',
    intro: 'The most closely examined year of the file. Standardised tests, external recognition, the university list, referees approached, and a summer given over to writing.' },
  3: { title: 'Application', when: 'Year 12 (Terminale)',
    intro: 'Four calendars overlap — British, American, European and French. The work becomes date-by-date navigation, where no deadline can be recovered.' },
  4: { title: 'Taking up the place', when: 'Once the offer is in hand',
    intro: 'An offer only counts if it is taken up. Visa, grade conditions to meet, settling in: the most underestimated phase, and the one where administrative delays still cost places every year.' },
};

export const UI_EN = {
  // Connexion
  loginEyebrow: 'Client area',
  loginTitle: "Follow your child's application",
  loginIntro: 'Enter the address you gave us. We will send you a sign-in link — there is no password to remember.',
  emailLabel: 'Email address',
  emailPlaceholder: 'you@example.com',
  loginSubmit: 'Send my link',
  loginSending: 'Sending…',
  loginSent: 'Link sent. Check your inbox — it is valid for one hour.',
  loginFailed: 'Sending failed',
  noFile: 'No application is linked to this address yet.<br>Write to us and we will give you access straight away.',
  discover: 'Explore our work',
  noFileYet: 'No file yet?',

  // Dossier
  file: 'File',
  nextDeadline: 'Next deadline',
  nothingDue: 'Nothing needs your attention',
  nothingDueSub: 'We will let you know as soon as something requires you.',
  focusTitle: 'What needs you right now',
  journey: 'The journey, step by step',
  currentYear: 'Current year',
  steps: 'steps',
  whoLabel: 'Who acts',
  allOwners: 'All',
  ownerYou: 'You',
  ownerChild: 'Your child',
  ownerCarmine: 'Carmine',
  nextNone: 'Nothing requires your attention',
  progress: (done, total, late) =>
    `${done} of ${total}${late ? ` · ${late} overdue` : ''}`,
  step: 'step',
  sessionNotes: 'Session notes',
  signOut: 'Sign out',
  consolidated: 'Consolidated calendar',
  allTracks: 'All tracks',
  pastTitle: 'steps predating the start of our work together',
  pastIntro: 'These steps come before our engagement began. They appear here for the record and do not represent a delay.',
  fileFollowed: 'File',

  // Panneau
  purpose: 'What this step is for',
  weProduce: 'What we produce',
  weExpect: 'What we need from you',
  people: 'Who is involved',
  watchOut: 'Worth knowing.',
  deadlineNature: 'The nature of this deadline',
  deadlineNatureBody: 'This date cannot be recovered. Reminders are sent at forty-five, twenty-one, ten and three days, then on the day itself.',
  documents: 'Documents',
  expectedDocs: 'Documents needed',
  templates: 'Related templates',
  dropFile: 'Upload a file',
  dropHint: 'PDF, image or document — click or drag here',
  noDocs: 'No documents uploaded.',
  uploading: 'Uploading…',
  progress: 'Progress',
  parentMessage: 'Message shown to parents',
  privateNote: 'Internal note — never visible to parents',
  save: 'Save',
  saved: 'Saved',
  close: 'Close',
  whereWeAre: 'Where we stand',

  // Statuts
  status: { a_faire: 'To do', en_cours: 'In progress', fait: 'Done', sans_objet: 'Not applicable' },

  // Délais
  today: 'today',
  tomorrow: 'tomorrow',
  overdueOne: 'one day overdue',
  overdue: (n) => `${n} days overdue`,
  inDays: (n) => `in ${n} days`,
  inOneMonth: 'in a month',
  inMonths: (n) => `in ${n} months`,

  // Classes
  classes: {
    sixieme: 'Year 7', cinquieme: 'Year 8', quatrieme: 'Year 9', troisieme: 'Year 10',
    seconde: 'Year 11', premiere: 'Year 12', terminale: 'Year 13', apres: 'After school',
  },
  tracks: { uk: 'United Kingdom', us: 'United States', eu: 'Europe' },
  kinds: { livrable: 'Deliverable', jalon: 'Milestone', document: 'Document', examen: 'Exam', formulaire: 'Form' },
  owners: { carmine: 'Carmine', eleve: 'Student', parents: 'Parents', etablissement: 'School', externe: 'External body' },

  // Pilotage
  steering: 'Steering',
  newFile: 'New file',
  needsAction: 'What needs action',
  files: 'Files',
  allClear: 'Nothing requires attention. Everything is on track.',
  student: 'Student', stepCol: 'Step', dueCol: 'Due', delayCol: 'Delay', statusCol: 'Status',
  overdueCount: 'overdue',
  allFiles: 'All files',
  resync: 'Realign calendar',
  addNote: 'Add a session note',
  createTitle: 'Create a file',
  createIntro: 'The full calendar is generated automatically from the current school year, all the way to the start of university.',
  firstName: 'First name',
  lastName: 'Surname',
  currentClass: 'Current year group',
  tracksLabel: 'Target countries',
  school: 'School',
  city: 'City',
  createSubmit: 'Create the file',
  creating: 'Creating…',
  cancel: 'Cancel',
  pickTrack: 'Select at least one track.',
  failed: 'Failed',
  noFiles: 'No files yet. Create the first one.',
  adminOnly: 'This page is restricted to administration.',
  goToClient: 'Go to your area',
  goToPilotage: 'Dashboard',
  notePromptTitle: 'Session note title',
  notePromptBody: 'Content',
  notePromptVisible: 'Make this note visible to parents?',
  noteVisible: 'visible to parents',
  notePrivate: 'private',
  summary: (n, late, urgent) =>
    `${n} active file${n > 1 ? 's' : ''}` +
    (late ? ` · ${late} overdue` : '') +
    ` · ${urgent} deadline${urgent > 1 ? 's' : ''} approaching`,
  hiddenRows: (n) => `${n} further deadlines not shown.`,
  resynced: (a, r, d) => `Calendar realigned: ${a} added, ${r} redated, ${d} removed.`,
};

/** Traductions des jalons, indexées par identifiant. */
export const MILESTONES_EN = {
  'A-01': {
    title: 'Diagnostic meeting and profile questionnaire',
    when: 'At the start of our work together',
    obj: 'To establish an accurate reading of the profile before any decision is taken: schooling, results, languages, genuine commitments, family constraints.',
    carmine: 'A written record of the diagnostic and a first hypothesis for the path ahead.',
    family: 'Complete the online profile questionnaire without filtering out what seems unremarkable to you.',
  },
  'A-02': {
    title: 'Long-term strategy note', when: 'Within a fortnight',
    obj: 'To settle the target countries and families of courses, and the reasoning behind them — so that it can later be revised knowingly.',
    carmine: 'A four to six page note: possible paths, consequences for schooling, overall calendar.',
    family: "Read it, challenge it, have your child read it. A strategy the student does not own will not survive three years.",
  },
  'A-03': {
    title: 'Choice of school or stream', when: 'Before school applications close',
    obj: 'To decide between the national system, an international section, the IB or a British curriculum. This choice determines how the file will be read abroad.',
    carmine: 'A costed comparison: how each qualification reads country by country, requirements, cost, and how reversible the choice is.',
    family: 'Tell us when the school application deadlines fall — they often come very early.',
  },
  'A-04': {
    title: 'Language plan', when: 'Reviewed each year',
    obj: 'To bring English to an academic level — following a lecture, writing a reasoned essay — and, if continental Europe is in view, to reach the level required in a second language.',
    carmine: 'An annual roadmap with target levels, resources and checkpoints.',
    family: 'Keep up the reading. It is the highest-yielding investment in the whole preparation.',
    warn: 'German at C1 governs access to undergraduate degrees at ETH Zurich and most German public universities. That is decided four years ahead, not six months.',
  },
  'A-05': {
    title: 'Mapping the student’s interests', when: 'End of Year 10',
    obj: 'To identify two or three genuine avenues of excellence rather than accumulating activities without direction.',
    carmine: 'An exploration workshop and a note steering commitments for the next three years.',
    family: 'Accept the pruning. Dropping three activities to go deeper into one is counter-intuitive and decisive.',
  },
  'A-06': {
    title: 'The US transcript opens', when: 'Start of Year 10',
    obj: 'To flag that this year counts as Grade 9: these grades will appear in the file sent to American universities.',
    carmine: 'A framing alert and a note on the subjects that will carry the most weight.',
    family: 'Simply tell your child. Knowing the year counts is usually enough to change how it is treated.',
    warn: 'A weaker year is never disqualifying — it can be explained, and clear improvement across later years is itself a valued signal.',
  },
  'B-01': {
    title: 'Choosing specialist subjects', when: 'February – March',
    obj: 'To choose the specialist subjects for the final two years according to the courses in view, rather than the other way round.',
    carmine: 'A decision note setting out, for each possible combination, which courses it opens and which it closes.',
    family: 'Consult us before the form is submitted, not after.',
    warn: 'Without Mathématiques Expertes, applications in mathematics, computer science or engineering to Oxford, Cambridge and Imperial are not admissible. The decision is made at fifteen.',
  },
  'B-02': {
    title: 'Annual activity plan', when: 'October',
    obj: 'To separate what should be deepened from what should be dropped. A long list without depth carries no weight.',
    carmine: 'A commitments table setting out, for each, the level aimed at and the year’s milestone.',
    family: 'Protect the time it needs: a serious commitment requires stable weekly slots.',
  },
  'B-03': {
    title: 'First substantial project begins', when: 'January',
    obj: 'To move the student from participant to author: to produce something that did not exist before.',
    carmine: 'A brief, a schedule of milestones and monthly follow-up.',
    family: "Don't do the project for your child. An admissions reader recognises adult work immediately.",
  },
  'B-04': {
    title: 'Diagnostic SAT sitting', when: 'Spring',
    obj: 'To measure the real gap to target scores, with nothing at stake and no record, in order to size the preparation.',
    carmine: 'A section-by-section report and an asymmetric preparation plan.',
    family: 'No preparation beforehand: a rehearsed diagnostic diagnoses nothing.',
    warn: 'The near-universal weak point for French students is Reading & Writing, not mathematics. Preparation must spend most of its time there.',
  },
  'B-05': {
    title: 'Choosing summer programmes', when: 'January – February',
    obj: 'To keep only selective programmes or genuine immersions. Paid-for stays without selection add nothing to the file.',
    carmine: 'A reasoned shortlist and support with the applications.',
    family: 'Move early: the best programmes close applications in January.',
  },
  'B-06': {
    title: 'Progress meeting with parents', when: 'June',
    obj: 'To review the year and confirm the path before Year 12.',
    carmine: 'A written review and a forty-five minute meeting.',
    family: 'Come with your doubts, including about the strategy itself.',
  },
  'C-01': {
    title: 'Costed positioning note', when: 'September',
    obj: 'To place the profile against the real medians of the universities in view: academic record, external recognition, tests.',
    carmine: 'A positioning note with an eighteen-month projection and the gaps to close.',
    family: 'Accept a frank reading. A flattering note serves no one.',
  },
  'C-02': {
    title: 'Super-curricular programme', when: 'October',
    obj: 'To feed the British application through the subject itself: reading, online courses, olympiads, research.',
    carmine: 'A personal reading list, a selection of online courses and a competition calendar.',
    family: 'Understand the distinction: in the UK the drama club does not count; the book read on the subject does.',
    warn: 'This is the most misunderstood cultural difference. A British application is judged on what extends the discipline, not on the richness of the personality.',
  },
  'C-03': {
    title: 'Entering olympiads and competitions', when: 'October – December',
    obj: 'To secure recognition from outside the school — the one element of the file no adviser can manufacture.',
    carmine: 'A dated list of relevant competitions and the preparation that goes with them.',
    family: 'Watch the entry dates, often handled by the school and sometimes forgotten.',
  },
  'C-04': {
    title: 'SAT or ACT preparation', when: 'December – March',
    obj: 'To bring the score up to the medians in view: 1520 to 1580 for the most selective universities.',
    carmine: 'A weekly plan, timed practice tests and error analysis by type.',
    family: 'Guarantee ten to twelve hours a week during the cycle. It is a real load on top of school.',
  },
  'C-05': {
    title: 'First official sitting', when: 'March or May',
    obj: 'To secure a baseline score early enough to leave room for two further sittings.',
    carmine: 'Registration checked and the resulting score analysed.',
    family: 'Book the session weeks ahead: centres fill up.',
  },
  'C-06': {
    title: 'Long list of universities', when: 'February',
    obj: 'To build a list of around twenty-five institutions across three bands of likelihood, then narrow it.',
    carmine: 'A comparison table: requirements, real cost, admission rates, fit with the profile.',
    family: 'Separate perceived prestige from genuine fit. This is often the hardest conversation.',
    warn: 'A safety is only a safety if it is financially sustainable and the student would actually go.',
  },
  'C-07': {
    title: 'Financial modelling', when: 'March',
    obj: 'To cost each university properly and identify the aid available, before the list is fixed.',
    carmine: 'A costed simulation per institution, including need-based aid and merit awards.',
    family: 'Give us an honest figure. A strategy built on an optimistic budget falls apart in April.',
    warn: 'A few American universities meet the full demonstrated need of international applicants without the request for aid counting against the application. Every other university takes it into account.',
  },
  'C-08': {
    title: 'Visits and information sessions', when: 'March – June',
    obj: 'To give the essays concrete material, and to leave a trace of interest where that is explicitly taken into account.',
    carmine: 'A contact log and a framework of questions to ask.',
    family: 'A well-prepared online session beats an expensive trip that goes unused.',
  },
  'C-09': {
    title: 'Approaching teacher referees', when: 'Before the summer break',
    obj: "To approach the two teachers who best know how the student works, early enough for them to write with perspective.",
    carmine: 'The request letter, the summary sheet to hand them, and the follow-up schedule.',
    family: 'Let the student make the request in person, themselves.',
    warn: 'A teacher approached in September writes a generic letter. Approached in May, they write it with perspective and examples.',
  },
  'C-10': {
    title: 'Second substantial project', when: 'April – September',
    obj: 'To reach recognition beyond the school: a regional prize, supervised research, a publication, a viable organisation.',
    carmine: 'Monthly support and introductions where they are possible.',
    family: 'Accept that it takes time. A credible project needs twelve to eighteen months.',
  },
  'C-11': {
    title: 'English certification', when: 'June – July',
    obj: 'To obtain IELTS or TOEFL at the required level, neither too early nor too late.',
    carmine: 'Requirements checked university by university, and targeted preparation.',
    family: 'Do not sit it before Year 12.',
    warn: 'IELTS and TOEFL are valid for two years only. Taken in Year 11, they expire before the university term begins.',
  },
  'C-12': {
    title: 'Second SAT or ACT sitting', when: 'June or August',
    obj: 'To consolidate the score: the average gain between two prepared sittings is sixty to a hundred and twenty points.',
    carmine: 'Comparative analysis and the decision on whether a third sitting is worthwhile.',
  },
  'C-13': {
    title: 'Registering for UK admissions tests', when: 'Mid-June to late September',
    obj: 'To register for the test required by the course in view: MAT, PAT, TMUA, ESAT, UCAT or LNAT depending on the subject.',
    carmine: 'A personal schedule, registration verified, and proof of it filed.',
    family: 'Send us the registration confirmation as soon as you receive it.',
    warn: 'This is the leading cause of mechanical failure in a British application. A missed registration voids the application, with no appeal and no resit.',
  },
  'C-14': {
    title: 'Admissions test preparation', when: 'July – October',
    obj: 'To prepare for a format with no equivalent in the French system: open problems under severe time pressure.',
    carmine: 'An eight to twelve week plan, worked past papers and timed simulations.',
    family: 'Build this into the summer. These papers cannot be prepared in two weekends.',
  },
  'C-15': {
    title: 'Writing the personal statement', when: 'July – August',
    obj: "To answer UCAS's three structured questions in four thousand characters, with no repetition between sections.",
    carmine: 'Four to six annotated drafts, from outline to final text.',
    family: 'Let the student write. A text rewritten by an adult shows in the first sentence.',
    warn: 'This single text serves all five choices. If the five courses share no common discipline it becomes impossible to write — the list must be built with that constraint in mind.',
  },
  'C-16': {
    title: 'Writing the main essay', when: 'July – August',
    obj: 'To write the six hundred and fifty words of the personal statement, the only place in the file where the student speaks in their own voice.',
    carmine: 'Five to eight annotated drafts, from raw material through to the final version.',
    family: 'Accept unexpected subjects: a failure, a tiny obsession, often say more than an account of success.',
    warn: 'The most common mistake is the essay as narrated CV, repeating what the file already says.',
  },
  'C-17': {
    title: 'Supplemental essays for early applications', when: 'August',
    obj: 'To write the essays specific to each university applied to early, including the familiar "why us".',
    carmine: 'An essay bank managed in waves, with considered reuse.',
    family: 'Protect August. It is the only time this work is possible without grades suffering.',
  },
  'C-18': {
    title: 'Progress meeting with parents', when: 'July',
    obj: 'To confirm the state of the file before the application year and set out the calendar ahead.',
    carmine: 'A written review and a detailed calendar for the next twelve months.',
  },
  'D-01': { title: 'US application opens', when: '1 August',
    obj: 'To create the common application to US universities and carry over the data entered last year.',
    carmine: 'A full check of everything entered before anything is submitted.' },
  'D-02': { title: 'UCAS application opens', when: 'Early September',
    obj: 'To create the British application and link it to the school, without which no reference can be sent.',
    carmine: 'Verification of the school link and of the qualifications entered.' },
  'D-03': { title: 'Final university list', when: 'September',
    obj: 'To settle the list for good: twelve to sixteen in the US, five in the UK, plus European applications.',
    carmine: 'A locked table giving, for each institution, the deadline, the test required and the documents needed.' },
  'D-04': { title: 'Activities and honours list', when: 'September',
    obj: 'To express ten activities and five honours in a hundred and fifty characters each — a writing exercise in its own right.',
    carmine: 'Every line ranked and reworded.' },
  'D-05': {
    title: 'Authorising release of school records', when: 'Before any letter is requested',
    obj: 'To waive the right to read one’s own letters of recommendation, a precondition for approaching anyone.',
    carmine: 'The choice explained, and confirmation that the signature is registered before invitations go out.',
    family: 'Waiving this right is the student’s choice, never an obligation — but a letter the student can read carries less weight with readers, who know it.',
    warn: 'A purely administrative step, regularly forgotten. Until it is signed, no teacher or school officer can submit anything.',
  },
  'D-06': {
    title: 'Predicted grades and school reference', when: 'Before 1 October',
    obj: 'To obtain predicted grades consistent with the requirements in view, and a structured reference.',
    carmine: 'The request letter to the head, a reference framework in the current format, and follow-up until it is in hand.',
    family: 'Approach the school early: the workload is heavy and covers several students at once.',
    warn: 'Predictions set too low make the application inadmissible; unrealistic ones undermine the school’s credibility. The balance is negotiated in advance.',
  },
  'D-07': {
    title: 'Documents submitted by the school', when: 'October – November',
    obj: 'To have the school submit everything outside the student’s control: transcript, school report and profile, counsellor letter, two teacher evaluations.',
    carmine: 'Coordination with the school, translation of the academic record, and drafting of the school profile where none exists.',
    family: 'Warn the school from the start of term: these documents are numerous and largely unknown in French lycées.',
    warn: 'A French lycée generally has neither a school profile nor a counsellor in the American sense. These documents must be built from scratch — several weeks of work to be started in September.',
  },
  'D-08': {
    title: 'Oxford, Cambridge and medicine deadline', when: '15 October, 6pm UK time',
    obj: 'To submit the UCAS application for Oxford or Cambridge, medicine, dentistry and veterinary science.',
    carmine: 'A full read-through of the application and the submission receipt filed.',
    family: 'Plan nothing else that week.',
    warn: 'No latitude whatsoever, down to the minute. Oxford and Cambridge cannot both be applied to in the same year.',
  },
  'D-09': {
    title: 'My Cambridge Application', when: '22 October, 6pm UK time',
    obj: 'To complete the form specific to Cambridge, required in addition to the UCAS application and under its own separate deadline.',
    carmine: 'Answers prepared, written work selected, and the requirements of the chosen college checked.',
    family: 'Do not relax after 15 October: a second deadline follows immediately.',
    warn: 'Formerly the SAQ. Cambridge no longer retrieves anything uploaded to UCAS: everything the university needs to read goes through this form or the college.',
  },
  'D-10': { title: 'Sitting the admissions tests', when: 'Late October',
    obj: 'To sit the paper within the fixed window. Only the autumn session counts for Oxford and Cambridge.',
    carmine: 'Final preparation and test-centre logistics.' },
  'D-11': {
    title: 'Written work', when: 'Early November',
    obj: 'To submit the marked classwork required by certain Oxford and Cambridge courses, mainly in arts and humanities.',
    carmine: 'The most revealing pieces selected, and the format required by each college checked.',
    family: 'Keep marked work from the final two years: it is asked for exactly as it is, teacher’s corrections included.',
  },
  'D-12': {
    title: 'Early application deadlines', when: '1 November',
    obj: 'To submit early applications, where admission rates are often two to three times those of the regular round.',
    carmine: 'Each application read through and every receipt filed.',
    family: 'Understand the commitment: a binding early application obliges the student to enrol if admitted.',
    warn: 'Committing before knowing the size of the financial aid award is a trap for any family that depends on it. That decision is made in September, not October.',
  },
  'D-13': { title: 'University of California application', when: '1 – 30 November',
    obj: 'To submit the application common to the California campuses, with four specific essays through a separate portal.',
    carmine: 'Support with the four essays, which are very different from the main one.' },
  'D-14': {
    title: 'Arts portfolios and athletic recruitment', when: 'October – December',
    obj: 'To assemble what falls outside the standard file: portfolio, audition recording, athletic footage, academic eligibility file.',
    carmine: 'The portfolio scoped, a recording schedule, and introductions to coaches where the athletic route is open.',
    family: 'Start months ahead: a demanding audition recording is prepared like a competition.',
    warn: 'The American athletic route runs on its own calendar, well ahead of the standard file, and requires a separate academic eligibility file.',
  },
  'D-15': {
    title: 'Interview preparation', when: 'November',
    obj: 'To prepare for a format that is not a motivational interview but a miniature tutorial: reasoning aloud in front of an unfamiliar problem.',
    carmine: 'Four to six mock interviews with subject specialists, each followed by a written debrief.',
    family: 'Set aside evening slots. These sessions are demanding and spread over a month.',
  },
  'D-16': { title: 'Oxford and Cambridge interviews', when: 'Early December',
    obj: 'To sit two to four interviews of twenty to forty-five minutes, often remotely.',
    carmine: 'Logistics, last-hour preparation and the debrief.' },
  'D-17': {
    title: 'Alumni interviews', when: 'November – February',
    obj: 'To take the interviews offered by alumni networks, usually remote, optional but never neutral.',
    carmine: 'Three mock interviews and a preparation framework per university.',
    family: 'Reply within twenty-four hours to any interview offer: slots close quickly.',
  },
  'D-18': {
    title: 'Early application results', when: 'Mid-December',
    obj: 'To receive the decision: admitted, rejected, or deferred to the regular round.',
    carmine: 'An analysis note and immediate revision of the strategy according to the outcome.',
    family: 'If the offer is binding, all other applications must be withdrawn within forty-eight hours.',
  },
  'D-19': { title: 'Regular round deadlines', when: '1 – 5 January',
    obj: 'To submit all remaining applications, each with its own supplemental essays.',
    carmine: 'The second wave of essays and a read-through of every application.' },
  'D-20': { title: 'Main UCAS deadline', when: 'Mid-January, 6pm UK time',
    obj: 'To submit the application for all other British universities.',
    carmine: 'A final read-through and the receipt filed.' },
  'D-21': {
    title: 'Netherlands and Sweden', when: '15 January',
    obj: 'To submit applications to Dutch capped-place programmes and to Swedish universities.',
    carmine: 'The file assembled and February’s decentralised selection prepared.',
    warn: 'Dutch programmes without capped places fall under a second deadline, on 1 May. Confusing the two costs a year.',
  },
  'D-22': {
    title: 'French national applications', when: 'Mid-January to March',
    obj: 'To secure a high-level French route, compatible with the international applications.',
    carmine: 'Choices built, motivation statements written, and the whole articulated with the rest of the calendar.',
    warn: 'The French calendar overlaps the British and American deadlines. December and January carry most of the year’s load.',
  },
  'D-23': {
    title: 'Financial aid applications', when: 'January – February',
    obj: 'To file aid applications on time, failing which the aid is lost even where admission is granted.',
    carmine: 'Support with completion, which is particularly detailed for non-resident families.',
    family: 'Gather tax assessments and evidence of income and assets in advance.',
  },
  'D-24': { title: 'Ireland', when: '1 February',
    obj: 'To apply through the Irish national portal, whose deadline falls markedly earlier than the others.',
    carmine: 'Conversion of the baccalauréat to the Irish points scale and follow-up of the application.' },
  'D-25': {
    title: 'Mid-year report', when: 'February',
    obj: 'To have the school send first-term final-year grades, required by almost every American university.',
    carmine: 'The reminder to the school and confirmation of transmission, application by application.',
    warn: 'A drop in final-year results can lead to an offer already made being withdrawn. This is not theoretical: it happens every year.',
  },
  'D-26': {
    title: 'Letters of continued interest', when: 'February – April',
    obj: 'To follow up usefully with universities that have deferred a decision or placed the application on a waiting list.',
    carmine: 'A letter tailored to each university, resting on genuinely new material.',
    warn: 'A follow-up with nothing new does more harm than good. One letter per university, no more.',
  },
  'D-27': { title: 'Switzerland', when: 'Late April',
    obj: 'To apply to the Swiss federal institutes of technology and universities.',
    carmine: 'Verification of qualification recognition conditions, which are reassessed each year.' },
  'D-28': { title: 'Results and aid awards', when: 'Mid-March to 1 April',
    obj: 'To receive regular-round decisions, together with the detail of the financial aid awarded.',
    carmine: 'A comparison table of the real net cost per university.' },
  'D-29': {
    title: 'Weighing offers and appealing aid', when: 'April',
    obj: 'To compare offers on real net cost, and to ask for an award to be reviewed where the circumstances justify it.',
    carmine: 'A costed decision note and the drafting of the review request.',
  },
  'D-30': { title: 'Final decision', when: '1 May',
    obj: 'To confirm enrolment and pay the deposit at the chosen university.',
    carmine: 'Verification of the arrangements and follow-through on withdrawals elsewhere.' },
  'D-31': { title: 'Firm and insurance choices', when: 'May – June',
    obj: 'To settle on a firm offer and an insurance offer, whose grade conditions must be genuinely attainable.',
    carmine: 'Analysis of the conditions and a recommendation.' },
  'D-32': { title: 'Netherlands — second deadline', when: '1 May',
    obj: 'To apply to Dutch programmes without capped places.',
    carmine: 'Verification of mathematics requirements, which are often decisive.' },
  'D-33': { title: 'Final examinations', when: 'June',
    obj: 'To achieve the grades on which the offers depend.',
    carmine: 'Conditions tracked and a fallback plan prepared should one not be met.' },
  'D-34': {
    title: 'Results day and UK clearing', when: 'July – August',
    obj: 'To confirm the offer against the results, or move to clearing if a condition is not met.',
    carmine: 'Cover on results day: immediate analysis, universities contacted, decisions taken within hours.',
    family: 'Be reachable that day, wherever you are. Places go within hours.',
    warn: 'Adjustment for better-than-expected results no longer exists. Self-releasing to aim higher is now irreversible: the original place is lost the moment it is released.',
  },
  'E-01': {
    title: 'Official admission document', when: 'May – July',
    obj: 'To obtain the document issued by the university — the American certificate of eligibility or the British confirmation of acceptance — without which no visa application can be lodged.',
    carmine: 'A line-by-line check: exact spelling of the name, dates, amounts, course title.',
    family: 'Report any error immediately, however minor.',
    warn: 'Any divergence between passport and admission document blocks the consular appointment, and correcting it takes weeks.',
  },
  'E-02': {
    title: 'Clearance for certain science courses', when: 'As soon as the offer is firm',
    obj: 'To obtain the clearance required for a range of sensitive science and engineering courses, a precondition for the visa.',
    carmine: 'Verification of whether the course is caught, and follow-up of the application.',
    warn: 'Processing times are long and variable. A course that is caught plus a late application costs the term, even though the offer is secure.',
  },
  'E-03': {
    title: 'Visa application', when: 'As soon as the admission document arrives',
    obj: 'To obtain the student visa within consular timescales that lengthen sharply over the summer.',
    carmine: 'The document list country by country, preparation for the consular interview, and follow-up until issue.',
    family: 'Book the appointment as soon as slots open, before you have gathered every document.',
    warn: 'A strict chain of dependencies: deposit paid, then admission document issued, then fees and surcharges settled, then the online form, then the appointment. Allow also for the proof of funds required over a minimum period, and the tuberculosis test imposed depending on country of residence.',
  },
  'E-04': { title: 'Accommodation', when: 'May – July',
    obj: 'To secure accommodation, in halls or the private market depending on the city and the timing.',
    carmine: 'A comparison of the options and support with applications, guarantor included.' },
  'E-05': { title: 'Settling-in formalities', when: 'July – August',
    obj: 'To settle health insurance — mandatory and expensive in the United States — the bank account and the phone.',
    carmine: 'A dated checklist, country by country.' },
  'E-06': { title: 'Course selection and placement tests', when: 'August',
    obj: 'To build a sustainable first semester: course choices shape the first-year average.',
    carmine: 'Advice on selection and preparation for placement tests.' },
  'E-07': { title: 'Closing review', when: 'September',
    obj: 'To close the engagement and open access to the alumni network.',
    carmine: 'A written review and introductions to students already on the ground.' },
};
