/**
 * English layer for the portal interface and phase headings.
 * Loaded on demand — French visitors never download it. Kept apart from the
 * milestone data so the public demo can load the interface without carrying
 * the reference material.
 */

export const PHASES_EN = {
  0: { title: 'Groundwork', when: 'Years 7 to 9 (6e – 3e)',
    intro: "No application is being written yet: a student is being built. School and track choices, language level, first genuine commitments. This is also the year the transcript US universities will read quietly opens." },
  1: { title: 'Foundations', when: 'Year 10 (Seconde)',
    intro: 'The year of decisions that shape everything else. The specialist subjects chosen in spring determine which courses remain open three years later. Activities are pruned and the first substantial project begins.' },
  2: { title: 'Building', when: 'Year 11 (Première)',
    intro: 'The most closely examined year of the file. Standardised tests, external recognition, the university list, referees approached, and a summer given over to writing.' },
  3: { title: 'Application', when: 'Year 12 (Terminale)',
    intro: 'Four calendars overlap — British, American, European and French. The work becomes date-by-date navigation, where no deadline can be recovered.' },
  4: { title: 'Taking up the place', when: 'Once the offer is in hand',
    intro: 'An offer only counts if it is taken up. Visa, grade conditions to meet, settling in: the most underestimated phase, and the one where administrative delays still cost places every year.' },
};

export const UI_EN = {
  // Steering — Summit section
  summitTitle: 'Summit — SAT preparation',
  summitEmpty: 'No Summit account yet. Every student who saves their progress will appear here.',
  summitGoal: 'Goal',
  summitLast: 'Latest test',
  summitBest: 'Best',
  summitSessions: 'Sessions',
  summitQuestions: 'Questions',
  summitSeen: 'Last activity',

  // Demo: locked panel shown instead of a step's detail
  demoLockTitle: 'Reserved for the families we work with',
  demoLockBody: "The detail of each step — the method, the questions to ask, the traps to avoid — is part of the programme. The demo shows the calendar; the method is passed on in session.",
  demoLockCta: 'Contact us',

  // Connexion
  loginEyebrow: 'Client area',
  loginTitle: "Follow your child's application",
  loginIntro: 'Enter the address you gave us and your password.',
  emailLabel: 'Email address',
  emailPlaceholder: 'you@example.com',
  passwordLabel: 'Password',
  passwordHint: 'Eight characters minimum.',
  loginSubmit: 'Sign in',
  working: 'One moment…',
  loginFailed: 'Failed',

  signupTitle: 'Create your access',
  signupIntro: 'Use the address you gave us: it is the one linked to your child’s file. Choose a password and you will not be asked for an email link again.',
  signupSubmit: 'Create my access',
  signupSent: 'Check your inbox: a message is waiting to confirm your address. There will not be another.',
  goToSignup: 'Create my access',

  resetTitle: 'Forgotten password',
  resetIntro: 'Enter your address and we will send you a link to choose a new one.',
  resetSubmit: 'Send the link',
  resetSent: 'Link sent. Check your inbox — it is valid for one hour.',
  linkDead: 'This link is no longer valid. Links work once only, and some mail providers open them before you do. Request a new one, or sign in if you already have a password.',
  linkFailed: 'Signing in through that link failed. Request a new one, or sign in with your password.',
  forgotPassword: 'Forgotten password',
  backToSignin: 'Back to sign in',

  newPasswordTitle: 'Choose a password',
  newPasswordIntro: 'It will replace the previous one, on every device.',
  newPasswordSubmit: 'Save and continue',
  changePassword: 'Change my password',
  noFile: 'No file is linked to this address.<br>If we have not spoken yet, write to us — your area opens when the engagement begins.',
  discover: 'Explore our work',
  noFileYet: 'No file yet?',

  // Démonstration publique
  demoTag: 'Example',
  demoIntro: 'This file is fictional. It shows the client area as a family sees it: the full step-by-step calendar, the session notes and the real state of play. Uploaded documents, our internal method and our exchanges only appear inside an open file.',
  demoCtaTitle: 'And for your child?',
  demoCtaBody: 'The calendar is built from their current year group and the countries they are aiming for. Write to us: we open your area, and your child’s, once the engagement begins.',
  demoCtaButton: 'Write to us',
  seeExample: 'See an example',
  demoInviteBody: 'Look through a complete student file, step by step, from Year 11 to the first day of university. No account to create.',

  // Dossier
  file: 'File',
  nextDeadline: 'Next deadline',
  nothingDue: 'Nothing needs your attention',
  nothingExpected: 'Nothing on your side at this step.',
  nothingDueSub: 'Your next deadlines will appear here as soon as something requires you.',
  focusTitle: 'What needs you right now',
  journey: 'The journey, step by step',
  currentYear: 'Current year',
  steps: 'steps',
  whoLabel: 'Who acts',
  allOwners: 'All',
  ownerYou: 'You',
  ownerChild: 'Your child',
  ownerCarmine: 'Carmine',
  nextNone: 'Nothing requires your attention',
  progressCount: (done, total, late) =>
    `${done} of ${total}${late ? ` · ${late} overdue` : ''}`,
  step: 'step',
  sessionNotes: 'Session notes',
  signOut: 'Sign out',
  consolidated: 'Consolidated calendar',
  allTracks: 'All tracks',
  pastTitle: 'steps predating the start of our work together',
  pastIntro: 'These steps come before our engagement began. They appear here for the record and do not represent a delay.',
  fileFollowed: 'File',

  // Panneau
  purpose: 'What this step is for',
  repereTag: 'Our method',
  repereBody: 'No university sets this date: it is a rhythm we give ourselves so as to arrive ready for the deadlines that cannot be recovered.',
  concerns: 'Applies to',
  concernsTitle: 'Who this concerns',
  weProduce: 'What we produce',
  weExpect: 'What we need from you',
  people: 'Who is involved',
  watchOut: 'Worth knowing.',
  methodTitle: 'How to run it — internal',
  loading: 'Loading…',
  questionsTitle: 'Questions to ask',
  trameMissing: 'This template is not in the database yet.',
  questionsCopy: 'Copy to pass on',
  questionsCopied: 'Copied',
  questionsIntro: 'To be adapted to the university in question, then passed on. Remind the student to note the name of whoever answers: an essay quoting a specific answer stands apart from one quoting a brochure.',
  wishesTitle: 'Universities you are drawn to',
  wishesIntro: 'List them freely, even the uncertain ones: this is where the conversation starts, not a commitment. A university missing from our reference tables belongs here just as much.',
  wishesIntroAdmin: 'The wishes the family has entered, as written. To be turned into targets below, or discussed.',
  wishesEmpty: 'No wishes entered yet.',
  wishesToDocument: (n) => `${n} institution${n > 1 ? 's' : ''} to document in the reference table.`,
  wishPlaceholder: 'Name of a university',
  selectionTitle: 'The selection retained',
  retained: 'Retained',
  retenuesCount: (n, total) => `${n} of ${total} under consideration retained.`,
  selectionEmpty: 'No university retained yet.',
  pickUniversity: 'Choose from the reference table…',
  admissionRate: 'Admission',
  testsNotApplicable: 'tests not applicable',
  bands: { ambitieuse: 'Reaches', plausible: 'Targets', probable: 'Likelies' },

  journalTitles: { lecture: 'Reading log', projet: 'Project notebook', essai: 'Essay bank', contact: 'Contact log' },
  journalIntros: {
    lecture: 'Three lines per book or course is enough. This log is what makes the Personal Statement writable in July — and it is exactly what the interview will probe.',
    projet: 'This notebook is not there to report to us: it is there for you, in October, when you have to tell this project in six hundred and fifty words. Note what you did and what you take from it. We read it together in session to dig, never to check.',
    essai: 'Every draft counts. Keep track of what works and what you cut: the essay bank is reused from one university to the next.',
    contact: 'One line per session attended or exchange had. What you note here will reappear word for word in the autumn “why us” essays.',
  },
  journalFields: {
    retenu: 'What I take from it',
    desaccord: 'What I disagree with',
    question: 'The question it opens',
  },
  journalHints: {
    retenu: 'The one idea you would keep if you could keep only one.',
    desaccord: 'Even partial disagreement. This is what you will be asked to defend.',
    question: 'What you would want to dig into next.',
  },
  journalEmpty: {
    lecture: 'Nothing yet. Add the first reading below — a title is enough to start.',
    projet: 'Nothing yet. Note below what you did the last time you worked on it.',
    essai: 'Nothing yet. Add a first essay below.',
    contact: 'Nothing yet. Note below the first session you attended.',
  },
  journalNew: { lecture: 'Title of the book, article or course', projet: 'What you did this time', essai: 'Essay title', contact: 'University and type of contact' },
  journalRefHint: 'Author, platform or link — optional',
  journalAdd: 'Add',
  journalRemove: 'Remove',
  journalAnnotated: 'annotated',
  journalToAnnotate: 'to annotate',
  journalCount: (done, total) => `${done} of ${total} annotated`,

  deadlineNature: 'The nature of this deadline',
  deadlineNatureBody: 'This date cannot be recovered. It stays at the top of your area as it draws closer.',
  documents: 'Documents',
  expectedDocs: 'Documents needed',
  templates: 'Related templates',
  dropFile: 'Upload a file',
  dropHint: 'PDF, image or document — click or drag here',
  noDocs: 'No documents uploaded.',
  uploading: 'Uploading…',
  progress: 'Progress',
  parentMessage: 'Message shown to parents',
  privateNote: 'Internal note — never visible to parents',
  save: 'Save',
  saved: 'Saved',
  savedAuto: 'Saved automatically',
  close: 'Close',
  whereWeAre: 'Where we stand',

  // Statuts
  status: { a_faire: 'To do', en_cours: 'In progress', fait: 'Done', sans_objet: 'Not applicable' },

  // Délais
  today: 'today',
  fromDate: 'From',
  untilDate: 'Until',
  tomorrow: 'tomorrow',
  overdueOne: 'one day overdue',
  overdue: (n) => `${n} days overdue`,
  inDays: (n) => `in ${n} days`,
  inOneMonth: 'in a month',
  inMonths: (n) => `in ${n} months`,

  // Classes
  classes: {
    sixieme: 'Year 7', cinquieme: 'Year 8', quatrieme: 'Year 9', troisieme: 'Year 10',
    seconde: 'Year 11', premiere: 'Year 12', terminale: 'Year 13', apres: 'After school',
  },
  tracks: { uk: 'United Kingdom', us: 'United States', eu: 'Europe' },
  kinds: { livrable: 'Deliverable', jalon: 'Milestone', document: 'Document', examen: 'Exam', formulaire: 'Form' },
  owners: { carmine: 'Carmine', eleve: 'Student', parents: 'Parents', etablissement: 'School', externe: 'External body' },

  // Pilotage
  // Ouverture des accès
  accessTitle: 'Access to this file',
  accessIntro: 'One address per person. Access opens immediately if they have signed in before; otherwise it activates at their first sign-in, from the client area.',
  accessCount: (n) => `${n} address${n > 1 ? 'es' : ''}`,
  accessEmpty: 'Nobody has access to this file yet.',
  accessPlaceholder: 'address@example.com',
  accessOpen: 'Open access',
  accessActive: 'Active',
  accessPending: 'Awaiting first sign-in',
  accessRemove: 'Remove',
  accessConfirmRemove: 'Remove this access? They will no longer see the file.',
  accessRoles: { parent: 'Parent', eleve: 'Student' },

  kpiFiles: 'Active files',
  kpiLate: 'Overdue steps',
  kpiSoon: 'Deadlines approaching',

  steering: 'Steering',
  newFile: 'New file',
  needsAction: 'What needs action',
  files: 'Files',
  allClear: 'Nothing requires attention. Everything is on track.',
  student: 'Student', stepCol: 'Step', dueCol: 'Due', delayCol: 'Delay', statusCol: 'Status',
  classCol: 'Year', progressCol: 'Progress',
  lastDoneCol: 'Last step completed', nextCol: 'Next deadline',
  outcomeCol: 'Deadline or outcome',
  filesOpen: 'Open', filesClosed: 'Closed', filesAll: 'All',
  noFilesHere: 'No file in this view.',
  admitted: 'Admitted, file closed',
  admissionLabel: 'Place taken up',
  nothingDoneYet: 'Nothing completed',
  fileComplete: 'File complete',
  overdueCount: 'overdue',
  allFiles: 'All files',
  resync: 'Realign calendar',
  addNote: 'Add a session note',
  createTitle: 'Create a file',
  createIntro: 'The full calendar is generated automatically from the current school year, all the way to the start of university.',
  firstName: 'First name',
  lastName: 'Surname',
  currentClass: 'Current year group',
  tracksLabel: 'Target countries',
  school: 'School',
  city: 'City',
  createSubmit: 'Create the file',
  creating: 'Creating…',
  cancel: 'Cancel',
  pickTrack: 'Select at least one track.',
  failed: 'Failed',
  noFiles: 'No files yet. Create the first one.',
  adminOnly: 'This page is restricted to administration.',
  goToClient: 'Go to your area',
  goToPilotage: 'Dashboard',
  adminHere: 'A family’s view — you are an administrator.',
  signedInAs: 'Signed in as',
  notePromptTitle: 'Session note title',
  notePromptBody: 'Content',
  notePromptVisible: 'Make this note visible to parents?',
  noteVisible: 'visible to parents',
  notePrivate: 'private',
  summary: (n, late, urgent) =>
    `${n} active file${n > 1 ? 's' : ''}` +
    (late ? ` · ${late} overdue` : '') +
    ` · ${urgent} deadline${urgent > 1 ? 's' : ''} approaching`,
  hiddenRows: (n) => `${n} further deadlines not shown.`,
  resynced: (a, r, d) => `Calendar realigned: ${a} added, ${r} redated, ${d} removed.`,
};

/** Traductions des jalons, indexées par identifiant. */
